### ISSUE TITLE
Lyrics are not present in the files

### ISSUE THREAD

**Issue by Toniob** [denizenging/picard-sozler#1]
Hi,

First, thank you for your work. It seems that your plugin is not working on my computer. I’m using the Flatpak version of Picard 2.12.3. I’ve loaded your plugin and it seems it is activated. But when I scan new files are write them, the lyrics are not in the tags. Should I do something else ? Am I missing something ? I’ve been to lrclib.net and the lyrics do exist. And it seems they’re nothing related to sozler in the logs (in debug).

Thanks

**Comment by protodeniz** [comment]
> Hi,
> 
> First, thank you for your work. It seems that your plugin is not working on my computer. I’m using the Flatpak version of Picard 2.12.3. I’ve loaded your plugin and it seems it is activated. But when I scan new files are write them, the lyrics are not in the tags. Should I do something else ? Am I missing something ? I’ve been to lrclib.net and the lyrics do exist. And it seems they’re nothing related to sozler in the logs (in debug).
> 
> Thanks

Hi,

Thanks for reaching out. It might be related to the length not being found or off by a certain amount. This is really essential since they are matched on the basis of artist, title, and duration of the file. One thing I you can do is to tweak with logging settings of Picard. When you open the logging window, it should be on the down left IIRC (or right). I can optionally test it myself. Would it be possible for me to access the files for further debugging?

Keep on rocking ^^

**Comment by Toniob** [comment]
I’ve put the log viewer in debug mode and I don’t see any message from your plugin. That’s why I wonder. Which version of Picard are you using ? Which OS ? Packaged or Flatpak ?

If you want to test, try for "let down" from "dead by sunrise" : https://lrclib.net/search/dead%20by%20sunrise%20let%20down . Here is an access to the file I use : https://cloud.6clones.net/s/wFRscoL5DMTToss (the link is available 7 days).

Thanks again a lot.

**Comment by protodeniz** [comment]
Hey, sorry for the late reply. I will get back to this as soon as I am available. It appears I will be busy for a week or two due to school. In the meanwhile, I think you could probably debug it if you know a little bit of Python.

**Comment by Toniob** [comment]
I’ve put the logs in picard in debug and I don’t see the "trying to query with" message in the logs. Is there a way to trigger the lyrics search ? Or I just have to add tracks ?

**Comment by Toniob** [comment]
Ok, my bad. I didn’t see that you have to activate a plugin in Picard when you install it. With the plugin activated, it’s working really fine. Really sorry. And thanks for your work. It helps a lot.

**Comment by protodeniz** [comment]
Haha. Sometimes things are the way they are. :) I am glad you were able to utilize the software.
